ignore:
  - "./actions/authActions.js"
  - "./actions/searchActions.js"
  - "./actions/cartActions.js"
  - "./screens/Course.js"
  - "./screens/Login.js"
  - "./screens/Profile.js"
  - "./screens/Cart.js"
  - "./sagas/authSagas"
  - "./sagas/searchSagas"
  - "./reducers"
  - "./components/Course"