ignore:
  - "./actions/authAction.js"
  - "./actions/authAction.js"
  - "./api"
  - "./screens/Course.js"
  - "./screens/Login.js"
  - "./screens/Profile.js"
  - "./screens/Cart.js"
  - "./sagas/authSagas"
  - "./reducers"
  - "./components/Course"
  - "./components/Searcher.js"